package ui;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author TheCrux
 */
public class RotationUI extends javax.swing.JPanel {

  public RotationUI() {
    initComponents();

    loadSettings();
  }

  public boolean useMount() {
    return jUseMount.isSelected();
  }

  public float getEatPercentage() {

    String text = jEatPercentage.getText();
    try {
      return 100 / Float.parseFloat(text);
    }
    catch (NumberFormatException e) {
      System.out.println("Invalid Eat Percentage: \"" + text + "\" -> " + e.getMessage());
      return 0;
    }
  }

  public float getDrinkPercentage() {
    String text = jDrinkPercentage.getText();
    try {
      return 100 / Float.parseFloat(text);
    }
    catch (NumberFormatException e) {
      System.out.println("Invalid Drink Percentage: \"" + text + "\" -> " + e.getMessage());
      return 0;
    }
  }

  private void loadSettings() {
    System.out.println("Loading combat settings.");

    DataInputStream in;
    try {
      in = new DataInputStream(new FileInputStream("./combatSettings.bin"));

      HashMap<String, String> prop = new HashMap<>();
      int propcount = in.read();
      for (int i = 0; i < propcount; i++) {
        int kl = in.read();
        byte[] b = new byte[kl];
        in.readFully(b);
        String key = new String(b);
        b = new byte[in.readInt()];
        in.readFully(b);
        prop.put(key, new String(b));
      }
      if (prop.size() > 0) {
        jUseMount.setSelected(Boolean.valueOf(prop.get("useMount")));
        jEatPercentage.setText(prop.get("eatPercentage"));
        jDrinkPercentage.setText(prop.get("drinkPercentage"));
      }
    }
    catch (IOException ex) {
      System.out.println("Couldn't load combat settings -> " + ex.getMessage());
      Logger.getLogger(RotationUI.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  private void saveSettings() {
    System.out.println("Saving combat settings.");

    DataOutputStream out;
    try {
      out = new DataOutputStream(new FileOutputStream(("./combatSettings.bin")));
      HashMap<String, String> props = new HashMap<>();

      props.put("eatPercentage", jEatPercentage.getText());
      props.put("drinkPercentage", jDrinkPercentage.getText());

      props.put("useMount", jUseMount.isSelected() ? "true" : "false");

      out.write(props.size());
      for (String s : props.keySet()) {
        byte[] b = s.getBytes();
        out.write(b.length);
        out.write(b);
        b = props.get(s).getBytes();
        out.writeInt(b.length);
        out.write(b);
      }
      out.flush();
      out.close();
    }
    catch (IOException ex) {
      System.out.println("Couldn't save combat settings -> " + ex.getMessage());
      Logger.getLogger(RotationUI.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jUseMount = new javax.swing.JCheckBox();
    jLabel2 = new javax.swing.JLabel();
    jEatPercentage = new javax.swing.JFormattedTextField();
    jLabel3 = new javax.swing.JLabel();
    jDrinkPercentage = new javax.swing.JFormattedTextField();

    jLabel1.setText("Rotation Settings");

    jUseMount.setText("Use Mount");
    jUseMount.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jUseMountActionPerformed(evt);
      }
    });

    jLabel2.setText("Eat Percentage");

    jEatPercentage.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
    jEatPercentage.setText("40");
    jEatPercentage.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jEatPercentageActionPerformed(evt);
      }
    });

    jLabel3.setText("Drink Percentage");

    jDrinkPercentage.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
    jDrinkPercentage.setText("40");
    jDrinkPercentage.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jDrinkPercentageActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jUseMount)
              .addComponent(jLabel2)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jEatPercentage, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDrinkPercentage, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
          .addGroup(layout.createSequentialGroup()
            .addGap(148, 148, 148)
            .addComponent(jLabel1)))
        .addContainerGap(155, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jLabel1)
        .addGap(8, 8, 8)
        .addComponent(jUseMount)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jEatPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jDrinkPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(130, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jUseMountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUseMountActionPerformed
    saveSettings();
  }//GEN-LAST:event_jUseMountActionPerformed

  private void jEatPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEatPercentageActionPerformed
    saveSettings();
  }//GEN-LAST:event_jEatPercentageActionPerformed

  private void jDrinkPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDrinkPercentageActionPerformed
    saveSettings();
  }//GEN-LAST:event_jDrinkPercentageActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JFormattedTextField jDrinkPercentage;
  private javax.swing.JFormattedTextField jEatPercentage;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JCheckBox jUseMount;
  // End of variables declaration//GEN-END:variables
}
